version: "3.8"
services: 
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - 4000:4000
    depends_on: 
      - mysql_server
  mysql_server:
    image: mysql:8.0
    environment: 
      - MYSQL_DATABASE=node_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
